"""empty message

Revision ID: d0391ef41937
Revises: 
Create Date: 2023-11-24 09:37:12.900672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0391ef41937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='设备id'),
    sa.Column('equipment_type', sa.Enum('摄像头', '录像机'), nullable=True, comment='设备类型'),
    sa.Column('manufacturer_type', sa.Enum('海康', '大华', '索尼', '宇视', '天地伟业', '三星'), nullable=True, comment='厂商类型'),
    sa.Column('equipment_name', sa.String(length=255), nullable=True, comment='设备名称'),
    sa.Column('equipment_ip', sa.String(length=32), nullable=True, comment='IP地址'),
    sa.Column('equipment_uname', sa.String(length=32), nullable=True, comment='用户名'),
    sa.Column('equipment_password', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('equipment_aisles', sa.Integer(), nullable=True, comment='通道'),
    sa.Column('equipment_codetype', sa.Enum('H265', 'H264'), nullable=True, comment='码流类型'),
    sa.Column('user_status', sa.String(length=32), server_default='1', nullable=True, comment='设备状态 1.启用 0.禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('preset_1', sa.String(length=255), nullable=True, comment='预置字段1'),
    sa.Column('preset_2', sa.String(length=255), nullable=True, comment='预置字段2'),
    sa.Column('preset_3', sa.String(length=255), nullable=True, comment='预置字段3'),
    sa.Column('Mine_id', sa.Integer(), nullable=True, comment='矿名称id'),
    sa.PrimaryKeyConstraint('id'),
    comment='设备表',
    mysql_engine='InnoDB'
    )
    op.create_table('t_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='菜单id'),
    sa.Column('menu_name', sa.String(length=32), nullable=True, comment='菜单名称'),
    sa.Column('menu_link', sa.String(length=255), nullable=True, comment='url请求地址'),
    sa.Column('menu_order', sa.Integer(), nullable=True, comment='菜单顺序'),
    sa.Column('menu_parent_id', sa.Integer(), nullable=True, comment='父菜单id'),
    sa.Column('menu_permission_list', sa.String(length=32), nullable=True, comment='权限标识列表'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表',
    mysql_engine='InnoDB'
    )
    op.create_table('t_mine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('mine_name', sa.String(length=100), nullable=True, comment='矿名称'),
    sa.PrimaryKeyConstraint('id'),
    comment='狂名称表',
    mysql_engine='InnoDB'
    )
    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='权限id'),
    sa.Column('permission_name', sa.String(length=32), nullable=True, comment='权限名称'),
    sa.Column('permission_code', sa.String(length=32), nullable=True, comment='权限代码'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表',
    mysql_engine='InnoDB'
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('username', sa.String(length=32), nullable=True, comment='用户名称'),
    sa.Column('password', sa.Text(), nullable=True, comment='用户密码'),
    sa.Column('email', sa.String(length=32), nullable=True, comment='用户邮箱'),
    sa.Column('user_status', sa.String(length=32), server_default='1', nullable=True, comment='账号状态 1.启用 0.禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('end_login_time', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mysql_engine='InnoDB'
    )
    op.create_table('t_user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联表id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('permission_id', sa.Integer(), nullable=True, comment='权限id'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户权限关联表',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user_permission')
    op.drop_table('t_user')
    op.drop_table('t_permission')
    op.drop_table('t_mine')
    op.drop_table('t_menu')
    op.drop_table('t_equipment')
    # ### end Alembic commands ###
